DROP DATABASE IF EXISTS twitch_drive;
CREATE DATABASE twitch_drive CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE twitch_drive;

CREATE TABLE usuarios(
  ID SERIAL PRIMARY KEY, /* BIGINT(16) UNSIGNED AUTO_INCREMENT*/
  NOMBRE VARCHAR(100),
  APELLIDO VARCHAR(100),
  AVATAR VARCHAR(44),
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR(40) NOT NULL,
  FECHA_ALTA DATETIME,
  FECHA_BAJA DATETIME,
  MOTIVO_BAJA ENUM('usuario','drive')
)ENGINE=innoDB;

CREATE TABLE recursos(
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(100),
  URL VARCHAR(100),
  TAMANIO INT(10) DEFAULT 0,
  FECHA_ALTA DATETIME,
  FECHA_LECTURA DATETIME,
  FECHA_MODIFICADO DATETIME,
  DESCRIPCION TEXT,
  TIPO_MIME VARCHAR(50),
  FKUSUARIO BIGINT(16) UNSIGNED,
  FKPARENT BIGINT(16) UNSIGNED,
  ES_DIRECTORIO TINYINT(1) DEFAULT 0,
  VISIBILIDAD ENUM('publico','compartido','privado'),


  CONSTRAINT RECURSO_USUARIO FOREIGN KEY(FKUSUARIO) REFERENCES usuarios(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  
  CONSTRAINT RECURSO_PADRE FOREIGN KEY(FKPARENT) REFERENCES recursos(ID) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=innoDB;

ALTER TABLE recursos ADD COLUMN DESTACADO TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE recursos ADD COLUMN ELIMINADO TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE recursos ADD COLUMN FECHA_ELIMINADO DATETIME DEFAULT NULL;

CREATE TABLE comparticiones(
  FKUSUARIO BIGINT(16) UNSIGNED,
  FKRECURSO BIGINT(16) UNSIGNED,
  FECHA_ALTA DATETIME,
  FECHA_VENCIMIENTO DATETIME,

  CONSTRAINT COMPARTICION_USUARIO FOREIGN KEY(FKUSUARIO) REFERENCES usuarios(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  
  CONSTRAINT COMPARTICION_RECURSO FOREIGN KEY(FKRECURSO) REFERENCES recursos(ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=innoDB;


CREATE TABLE recuperar(
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  FECHA_ALTA DATETIME,
  NUEVA_CLAVE VARCHAR(50)
)ENGINE=innoDB;